sudo: required
dist: trusty
language: python
python:
  - "2.7"

before_install:
 - "sudo apt-get -qq update"
 - "sudo apt-get install -y -qq gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev xterm"
script: "./travis/bbtest.sh"
